# Generated by Django 4.0.6 on 2022-07-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rate',
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
