# Generated by Django 4.0.6 on 2022-07-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('shop', '0003_remove_review_rate_product_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='caption',
        ),
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.CharField(default='without', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
