# Generated by Django 4.0.6 on 2022-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_rate_review_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
