# Generated by Django 4.0.6 on 2022-07-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_firstname_user_lastname_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
