# Generated by Django 4.0.6 on 2022-07-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.storeproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
