# Generated by Django 4.0.6 on 2022-07-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_delete_productorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_address',
        ),
    ]
