# Generated by Django 4.0.6 on 2022-07-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_customer_order_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='count',
        ),
    ]
