# Generated by Django 4.0.6 on 2022-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
