# Generated by Django 4.0.6 on 2022-07-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='count',
        ),
    ]
